server:
  port: 6005
  servlet:
    context-path: /javaAlgorithmService

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: java-algorithm-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost
        username: nacos
        password: nacos

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/tencent?characterEncoding=UTF-8
      username: root
      password: zw123456~!

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 150000
        loggerLevel: basic

logging:
  config: classpath:logback-spring.xml